backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# These lines should *not* be indented
media_folder: "checkpoint/src/assets/images" 
public_folder: "/images" 

collections:
  - name: "hosts" # Used in routes, e.g., /admin/collections/blog
    label: "Hosts" # Used in the UI
    folder: "checkpoint/cms/hosts" # The path to the folder where the documents are stored
    extension: "json"
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Order", name: "order", widget: "number", value_type:"int"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Profile Picture", name: "profilepic", widget: "image"}
      - {label: "Body", name: "body", widget: "text"}
      - {label: "Link", name: "link", widget: "string", required: false}
      - {label: "Link Title", name: "link_title", widget: "string", required: false}
      - {label: "Link 2", name: "link2", widget: "string", required: false}
      - {label: "Link Title 2", name: "link_title2", widget: "string", required: false}
      - {label: "Link 3", name: "link3", widget: "string", required: false}
      - {label: "Link Title 3", name: "link_title3", widget: "string", required: false}

  - name: "podcasts" # Used in routes, e.g., /admin/collections/blog
    label: "Podcasts" # Used in the UI
    folder: "checkpoint/cms/podcasts" # The path to the folder where the documents are stored
    extension: "json"
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Headline", name: "headline", widget: "text"}
      - {label: "Hosts", name: "hosts", widget: "text"}
      - {label: "Spotify Link", name: "link_spotify", widget: "string"}
      - {label: "Apple Music Link", name: "link_apple", widget: "string"}
  
  - name: "extras"
    label: "Extras"
    files:
      - label: "Header"
        name: 'header'
        file: "checkpoint/src/cms/header.json"
        fields: 
          - {label: "Main Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}

      - label: "Socials and Contact"
        name: 'socials'
        file: "checkpoint/src/cms/socials.json"
        fields: 
          - {label: "Email Address", name: "email", widget: "string"}
          - {label: "Twitter Handle", name: "twitter", widget: "string"}
          - {label: "Spotify Show URL (open.spotify.com)", name: "spotifyURL", widget: "string"}
          - {label: "Apple Podcast URL (podcasts.apple.com)", name: "appleURL", widget: "string"}
          - {label: "Audible URL", name: "audibleURL", widget: "string"}

